# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-03 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20180619_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='answer',
            field=models.TextField(blank=True, default='未回答', verbose_name='回答'),
        ),
        migrations.AddField(
            model_name='post',
            name='question',
            field=models.TextField(default='None', verbose_name='提问'),
        ),
    ]
