# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-03 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20190303_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialog',
            old_name='answer',
            new_name='answer1',
        ),
        migrations.RemoveField(
            model_name='dialog',
            name='question',
        ),
        migrations.AddField(
            model_name='dialog',
            name='answer2',
            field=models.TextField(blank=True, null=True, verbose_name='回答'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='answer3',
            field=models.TextField(blank=True, null=True, verbose_name='回答'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='answer4',
            field=models.TextField(blank=True, null=True, verbose_name='回答'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='id',
            field=models.TextField(default=1, max_length=50, primary_key=True, serialize=False, verbose_name='会话组'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dialog',
            name='question1',
            field=models.TextField(null=True, verbose_name='提问'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='question2',
            field=models.TextField(null=True, verbose_name='提问'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='question3',
            field=models.TextField(null=True, verbose_name='提问'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='question4',
            field=models.TextField(null=True, verbose_name='提问'),
        ),
    ]
