# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-03 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_auto_20190303_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dialog',
        ),
        migrations.DeleteModel(
            name='Dialog',
        ),
    ]
